name: Android CI

on:
  pull_request:
    branches: [ main, master, development ]
  push:
    branches: [ feature/**, fix/**, refactor/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configure o JDK
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    # 3. Checar se o commit contém DADOS SENSÍVEIS
    - name: Secret Scanning (dados sensíveis)
      run: |
        gh secret-scanning scan-repo \
        --repo "$GITHUB_REPOSITORY" \
        --sarif \
        --token "${{ secrets.GITHUB_TOKEN }}" \
        > results.sarif


    # 4. Dar permissão ao gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 5. Build do projeto
    - name: Build Android Project
      run: ./gradlew assembleDebug --stacktrace

    # 6. Rodar testes
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    # 7. Análise estática (lint)
    - name: Run Android Lint
      run: ./gradlew lint

    # 8. Verificar vulnerabilidades
    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'HIGH,CRITICAL'

